server:
  port: 8383

spring:
  datasource:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:demo-cricket
    username: sa
    password:
  h2:
    console:
      enabled: true
  hsqldb:
    name: demo-cricket
    username: sa
    password:
  hibernate:
    ddl-auto: update

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
